
version: '3.8'

services:

  backend:
    image: 902424/real-estate-rental-system:v1.0.509 # Reads version from the VERSION file
    container_name: backend
    platform: linux/x86_64
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: rsrs
      DB_PASSWORD: root
      SERVER_PORT: "8080"
    restart: always
    volumes:
      - ./logs/springboot.log:/app/logs/application.log
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  mysql_data: